name: Code styling
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  container-job:
    name: Prettier code styling
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Setup Node.js 22.x
        uses: actions/setup-node@v6
      - name: Install npm packages
        working-directory: ./ui
        run: npm ci --ignore-scripts
      - name: Check code style
        working-directory: ./ui
        run: npm run prettier:check
